modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="snowcoated"
version="${file.jarVersion}"
displayName="Snow Coated API"
updateJSONURL="https://github.com/supermassimo/SnowCoated/blob/main/version_info.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-coated"
#logoFile=""
#credits=""
authors="Max Hyper"
description='''
This is a small mod that allows customization of what blocks snow layers can be placed on.
'''

[[dependencies.snowcoated]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.snowcoated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
